version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: local_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: custweb
    volumes:
      - local_mysql:/var/lib/mysql
  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "5050:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: dracula

volumes:
  local_mysql: